export type Track = {
  id: string;
  videoId: string;
  dev: string;
  lat: string;
  assumedDuration: number;
  /** YouTube view count when the list was last refreshed (Sep 2026). */
  views: number;
};

/**
 * Ordered by YouTube view count, most-watched first — counts read off
 * YouTube in September 2026 and stored on each track so the ordering can be
 * checked (and refreshed) later.
 */
export const PLAYLIST: Track[] = [
  {
    id: "gulabi-sharara",
    videoId: "4cw3x0tU-pk",
    dev: "गुलाबी शरारा",
    lat: "Gulabi Sharara — Inder Arya & Neeru",
    assumedDuration: 239,
    views: 364051439,
  },
  {
    id: "dhana",
    videoId: "0hS7ti5PS5A",
    dev: "धाना",
    lat: "Dhana — Priyanka Meher & Rongpaz",
    assumedDuration: 235,
    views: 85049783,
  },
  {
    id: "cream-paudara",
    videoId: "-r-PMDXH3as",
    dev: "क्रीम पौडरा",
    lat: "Cream Paudara — Rakesh Khanwal & Maya Upadhyay",
    assumedDuration: 327,
    views: 82147348,
  },
  {
    id: "thal-ki-bazar",
    videoId: "ijN3PK7j6PQ",
    dev: "थल की बाजार",
    lat: "Thal Ki Bazar — B.K. Samant",
    assumedDuration: 204,
    views: 70330833,
  },
  {
    id: "fwa-bagha-re",
    videoId: "6jMJCe2_9Vk",
    dev: "फ्वां बाघा रे",
    lat: "Fwa Bagha Re — Pappu Karki",
    assumedDuration: 298,
    views: 63358300,
  },
  {
    id: "ghumai-de",
    videoId: "Wgbl6E8zqV8",
    dev: "घुमै दे",
    lat: "Ghumai De — Priyanka Meher & Rongpaz",
    assumedDuration: 237,
    views: 56772185,
  },
  {
    id: "chaita-ki-chaitwali",
    videoId: "qhJ2htuDjlg",
    dev: "चैता की चैत्वाली",
    lat: "Chaita Ki Chaitwali — Amit Saagar",
    assumedDuration: 417,
    views: 50749176,
  },
  {
    id: "sawri-sawri",
    videoId: "1vEU8DJp1Wg",
    dev: "सौंरी सौंरी (मेरी माधुरी)",
    lat: "Sawri Sawri — Inder Arya",
    assumedDuration: 277,
    views: 47073111,
  },
  {
    id: "dhai-hathe-dhameli",
    videoId: "MVYkoXd_KZA",
    dev: "ढाई हाथे धमेली",
    lat: "Dhai Hathe Dhameli — Manoj Arya & Priyanka Meher",
    assumedDuration: 336,
    views: 44477269,
  },
  {
    id: "tero-lehenga-2",
    videoId: "N0owZ4Nkhns",
    dev: "तेरो लहंगा 2",
    lat: "Tero Lehenga 2 — Avinash Rana & Inder Arya",
    assumedDuration: 194,
    views: 44206223,
  },
  {
    id: "hey-madhu",
    videoId: "1ipJZHXol-U",
    dev: "हे मधु",
    lat: "Hey Madhu — Inder Arya",
    assumedDuration: 288,
    views: 43290205,
  },
  {
    id: "mai-pahadan",
    videoId: "dPExLKarsyo",
    dev: "मैं पहाड़न",
    lat: "Mai Pahadan — Mamta Arya",
    assumedDuration: 416,
    views: 42624633,
  },
  {
    id: "ab-laglu-mandaan",
    videoId: "0RjvMBr3tdk",
    dev: "अब लग्लु मंडाण",
    lat: "Ab Laglu Mandaan — Ruhaan Bhardwaj & Karishma Shah",
    assumedDuration: 293,
    views: 42013169,
  },
  {
    id: "fyonladiya",
    videoId: "GsqdP7lzdWM",
    dev: "फ्योंलड़िया",
    lat: "Fyonladiya — Kishan Mahipal",
    assumedDuration: 430,
    views: 35691276,
  },
  {
    id: "uk-rapi-boy",
    videoId: "JSb_4gahFuY",
    dev: "यूके रैपी बॉय",
    lat: "Uk Rapi Boy — Priyanka Meher",
    assumedDuration: 287,
    views: 35292392,
  },
  {
    id: "jai-bhole",
    videoId: "yru_nPYlKzc",
    dev: "जय भोले",
    lat: "Jai Bhole — Kuldeep Kaprwan & Hema Negi Karasi",
    assumedDuration: 409,
    views: 33878096,
  },
  {
    id: "meri-bamani",
    videoId: "vUwtyHtgE80",
    dev: "मेरी बामणी",
    lat: "Meri Bamani — Hema Negi Karasi",
    assumedDuration: 482,
    views: 33542861,
  },
  {
    id: "modern-kumaun",
    videoId: "EzFih09wwX8",
    dev: "मॉडर्न कुमाऊँ",
    lat: "Modern Kumaun — Inder Arya",
    assumedDuration: 275,
    views: 32271098,
  },
  {
    id: "sapna-syali",
    videoId: "2WhxpNHxuD0",
    dev: "सपना स्याली",
    lat: "Sapna Syali — Sanjay Bhandari & Saurav Maithani",
    assumedDuration: 409,
    views: 31743924,
  },
  {
    id: "chhal-kapat",
    videoId: "S_fPNQYoQaQ",
    dev: "छल कपट",
    lat: "Chhal Kapat — Garhwali Hit (BK Sangeet)",
    assumedDuration: 382,
    views: 31726617,
  },
  {
    id: "chori-chandra",
    videoId: "RIoDWD2M-D4",
    dev: "छोरी चंद्रा",
    lat: "Chori Chandra — Rohit Chauhan & Avinash Rana",
    assumedDuration: 239,
    views: 31437299,
  },
  {
    id: "ramdai-ka-hotel",
    videoId: "Tx2uEx5yxx4",
    dev: "रामदई का होटल",
    lat: "Ramdai Ka Hotel — Satendra Gangola",
    assumedDuration: 319,
    views: 28973253,
  },
  {
    id: "bol-heera",
    videoId: "DhJGyNAYwio",
    dev: "बोल हीरा",
    lat: "Bol Heera — Inder Arya",
    assumedDuration: 310,
    views: 27872420,
  },
  {
    id: "sobanu",
    videoId: "oIkX-e8rPXg",
    dev: "सोबनु",
    lat: "Sobanu — Hema Negi Karasi",
    assumedDuration: 290,
    views: 27731197,
  },
  {
    id: "jiya-kori-kori-khando",
    videoId: "Sfd5X--L9Zc",
    dev: "जिया कोरी कोरी खांदो",
    lat: "Jiya Kori Kori Khando — Kishan Mahipal & Tanu Rawat",
    assumedDuration: 438,
    views: 27702073,
  },
  {
    id: "dhol-damau-baji-gena",
    videoId: "oCW36G_9YYA",
    dev: "ढोल दमौ बाजी गेना",
    lat: "Dhol Damau Baji Gena — Sangeeta Dhoundiyal",
    assumedDuration: 347,
    views: 27587482,
  },
  {
    id: "pink-plazo",
    videoId: "ElIk4bTn6sg",
    dev: "पिंक प्लाजो",
    lat: "Pink Plazo — Suryapal Shriwan & Anisha Ranghar",
    assumedDuration: 314,
    views: 26795901,
  },
  {
    id: "himuli",
    videoId: "fsrQLToqu9E",
    dev: "हिमुली",
    lat: "Himuli — Rakesh Khanwal & Mamta Arya",
    assumedDuration: 482,
    views: 25572482,
  },
  {
    id: "kajal-kajal",
    videoId: "lCVcwug1-8o",
    dev: "काजल काजल",
    lat: "Kajal Kajal — Anisha Ranghar & Madhusudan Nautiyal",
    assumedDuration: 271,
    views: 24376285,
  },
  {
    id: "chaha-ko-hotel",
    videoId: "rPiUSs8JE6Y",
    dev: "चहा को होटल",
    lat: "Chaha Ko Hotel — Manoj Arya & Maya Upadhyay",
    assumedDuration: 261,
    views: 23798001,
  },
  {
    id: "suretu-mama",
    videoId: "rxFs_SZXYSc",
    dev: "सुरेतु मामा",
    lat: "Suretu Mama — Manju Nautiyal (Jaunsari Harul)",
    assumedDuration: 311,
    views: 23426752,
  },
  {
    id: "hey-nanda",
    videoId: "TK8uvD-MDkE",
    dev: "हे नंदा",
    lat: "Hey Nanda — Darshan Farswan",
    assumedDuration: 275,
    views: 23142322,
  },
  {
    id: "challpatti",
    videoId: "IHbmTexI_O4",
    dev: "छलपत्ती",
    lat: "Challpatti — Diwan Singh Panwar & Meena Rana",
    assumedDuration: 250,
    views: 22612243,
  },
  {
    id: "jhumki-darshan-farswan",
    videoId: "1kt9HqV9ICo",
    dev: "झुमकी",
    lat: "Jhumki — Darshan Farswan",
    assumedDuration: 260,
    views: 22281153,
  },
  {
    id: "pahadon-ko-raibasi",
    videoId: "sjiphyYu07k",
    dev: "पहाड़ों को रैबासी",
    lat: "Pahadon Ko Raibasi — Saurav Maithani & Anjali Kharre",
    assumedDuration: 425,
    views: 22259839,
  },
  {
    id: "hit-madhuli",
    videoId: "9W49GjmzwaY",
    dev: "हिट मधुली",
    lat: "Hit Madhuli — Inder Arya",
    assumedDuration: 340,
    views: 21988827,
  },
  {
    id: "kwi-ta-baat-holi",
    videoId: "S-Q8YOdkaIA",
    dev: "क्वी त् बात होलि",
    lat: "Kwi Ta Baat Holi — Narendra Singh Negi",
    assumedDuration: 309,
    views: 21812867,
  },
  {
    id: "nug-badiya",
    videoId: "0SSQTx3CDng",
    dev: "नुग बड़िया",
    lat: "Nug Badiya — Diksha Dhoundiyal",
    assumedDuration: 231,
    views: 21122316,
  },
  {
    id: "jhumki-priyanka-meher",
    videoId: "i8LI1nCuINc",
    dev: "झुमकी",
    lat: "Jhumki — Priyanka Meher",
    assumedDuration: 262,
    views: 20824853,
  },
  {
    id: "lal-botal-saraba",
    videoId: "iaQbiSvFfjs",
    dev: "लाल बोतल शराबा",
    lat: "Lal Botal Saraba — Prakash Kahala",
    assumedDuration: 309,
    views: 20728464,
  },
  {
    id: "batu-chh-samwar",
    videoId: "KwfU54k2ZxA",
    dev: "बटू छ समवार",
    lat: "Batu Chh Samwar — Narendra Singh Negi & Manju Sundriyal",
    assumedDuration: 490,
    views: 4711591,
  },
  {
    id: "ghuguti-ghuraona-laigi",
    videoId: "AwESlAx6py8",
    dev: "घुघुती घुरोणा लगि",
    lat: "Ghuguti Ghuraona Laigi — Meena Rana",
    assumedDuration: 296,
    views: 3640868,
  },
  {
    id: "ranchana",
    videoId: "h2h1GyOEPlc",
    dev: "रञ्चणा",
    lat: "Ranchana — Pandavaas",
    assumedDuration: 432,
    views: 3585896,
  },
  {
    id: "min-ta-suni-tera-gaon-ma",
    videoId: "Tbu166qirVQ",
    dev: "मीं त सुणी तेरा गौं मा",
    lat: "Min Ta Suni Tera Gaon Ma — N.S. Negi & Meena Rana",
    assumedDuration: 336,
    views: 2685532,
  },
  {
    id: "hey-ramiye",
    videoId: "O_tWjS7xj7o",
    dev: "हे रामियै",
    lat: "Hey Ramiye — N.S. Negi & Meena Rana",
    assumedDuration: 398,
    views: 2002760,
  },
  {
    id: "ghughuti-2",
    videoId: "2Bugm8QWu2E",
    dev: "घुघुती",
    lat: "Ghughuti — Kishan Mahipal",
    assumedDuration: 379,
    views: 1940457,
  },
  {
    id: "ghasyari",
    videoId: "D2Opsod0KMc",
    dev: "घसियारी",
    lat: "Ghasyari — Jitendra Tomkyal & Mamta Arya",
    assumedDuration: 451,
    views: 1450291,
  },
  {
    id: "ghughuti-basuti",
    videoId: "m2E_0XLNLLw",
    dev: "घुघुती बासुती",
    lat: "Ghughuti Basuti — Pandavaas",
    assumedDuration: 282,
    views: 1391911,
  },
  {
    id: "paili-tin-rupako-jadu-chalai",
    videoId: "WBTrfpmgUpo",
    dev: "पैली तीन रुपाको जादू चलाई",
    lat: "Paili Tin Rupako Jadu Chalai — N.S. Negi & Meena Rana",
    assumedDuration: 335,
    views: 1383473,
  },
  {
    id: "mwaari",
    videoId: "xOEumxQp1gM",
    dev: "म्वारी",
    lat: "Mwaari — Pandavaas",
    assumedDuration: 330,
    views: 883363,
  },
  {
    id: "basanti-danda",
    videoId: "SkKb-6LKfXQ",
    dev: "हिट बसंती डांडा",
    lat: "Basanti Danda — Dr. Pritam Bhartwan",
    assumedDuration: 348,
    views: 787411,
  },
  {
    id: "chandna-mera-pahaad",
    videoId: "TbJNa9c9U3A",
    dev: "चांदना मेरा पहाड़",
    lat: "Chandna Mera Pahaad — Meena Rana",
    assumedDuration: 254,
    views: 770081,
  },
  {
    id: "o-neera",
    videoId: "yOSRckPVAGo",
    dev: "ओ नीरा",
    lat: "O Neera — Gajendra Rana",
    assumedDuration: 440,
    views: 669119,
  },
  {
    id: "ghas-gadoli",
    videoId: "OvynTJPAQKg",
    dev: "घास गडोली",
    lat: "Ghas Gadoli — Anuradha Nirala",
    assumedDuration: 473,
    views: 493630,
  },
  {
    id: "saira-gaon",
    videoId: "rZXJ8Q-0LtI",
    dev: "सैरा गौं",
    lat: "Saira Gaon — Pandavaas",
    assumedDuration: 312,
    views: 480889,
  },
  {
    id: "bhana-ye-rangili-bhana",
    videoId: "fH-xQkW0bbw",
    dev: "भाना ये रंगीली भाना",
    lat: "Bhana Ye Rangili Bhana — Chandra Singh Rahi",
    assumedDuration: 382,
    views: 277991,
  },
  {
    id: "yaad-tera-gaon-ki",
    videoId: "wjr9ocgAUyk",
    dev: "याद तेरा गांव की",
    lat: "Yaad Tera Gaon Ki — Gajendra Rana",
    assumedDuration: 297,
    views: 233361,
  },
  {
    id: "dwarahat-bazaar",
    videoId: "vPX80OOHrEo",
    dev: "द्वाराहाट बाजार",
    lat: "Dwarahat Bazaar — Jitendra Tomkyal",
    assumedDuration: 304,
    views: 211239,
  },
  {
    id: "rasyann",
    videoId: "C1vHqeVmcfY",
    dev: "रस्यंण",
    lat: "Rasyann — Anuradha Nirala",
    assumedDuration: 328,
    views: 190401,
  },
  {
    id: "kamla-bimla-himla",
    videoId: "AysSTrCGCYs",
    dev: "कमला बिमला हिमला",
    lat: "Kamla Bimla Himla — Gajendra Rana",
    assumedDuration: 298,
    views: 104103,
  },
  {
    id: "mai-si-nafrat",
    videoId: "nqXqB01rSBw",
    dev: "मैं सी नफरत",
    lat: "Mai Si Nafrat — Keshar Panwar, Meena Rana",
    assumedDuration: 346,
    views: 75972,
  },
  {
    id: "ringa-ring",
    videoId: "cN7PEc2hQJk",
    dev: "रिंगा रिंग",
    lat: "Ringa Ring — Meena Rana & Sanjay Kumola",
    assumedDuration: 405,
    views: 69297,
  },
  {
    id: "yo-pahad-ma",
    videoId: "NmwtS1GnX5k",
    dev: "यो पहाड़ मा",
    lat: "Yo Pahad Ma — Jitendra Tomkyal",
    assumedDuration: 336,
    views: 38143,
  },
  {
    id: "jara-thandu-chala-di",
    videoId: "j3cE90Tv6y0",
    dev: "जरा ठंडू चला दी",
    lat: "Jara Thandu Chala Di — Chandra Singh Rahi",
    assumedDuration: 329,
    views: 3251,
  },
  {
    id: "mohan-girdhari",
    videoId: "rEmP8sclk_k",
    dev: "मोहन गिरधारी",
    lat: "Mohan Girdhari — Kumaoni Holi Song",
    assumedDuration: 217,
    views: 849,
  },
  {
    id: "aija-agni",
    videoId: "aLPe3zgEUt4",
    dev: "आईजा अग्नि आईजा अग्नि",
    lat: "Aija Agni Aija Agni (Mangal) — Narendra Singh Negi",
    assumedDuration: 447,
    views: 764,
  },
  {
    id: "bedu-pako",
    videoId: "T7GhubZGBIg",
    dev: "बेडु पाको बारो मासा",
    lat: "Bedu Pako Baro Masa — Traditional Kumaoni",
    assumedDuration: 395,
    views: 230,
  },
];

/** Fixed reference instant every visitor's clock math is anchored to. */
export const SCHEDULE_EPOCH = Date.parse("2025-01-01T00:00:00Z");

export type ScheduleResult = { index: number; offset: number };

/**
 * Picks "the track that should be playing right now" the same way for every
 * visitor, purely from wall-clock time — no server round trip needed.
 * `durations` lets callers substitute real (player-reported) lengths in
 * place of the shipped estimates once known, so the schedule self-corrects.
 */
export function scheduleFromEpoch(
  durations: Record<string, number> = {},
  now: number = Date.now(),
): ScheduleResult {
  const lengths = PLAYLIST.map((t) => durations[t.videoId] ?? t.assumedDuration);
  const totalCycle = lengths.reduce((a, b) => a + b, 0);
  let elapsed = ((now - SCHEDULE_EPOCH) / 1000) % totalCycle;
  if (elapsed < 0) elapsed += totalCycle;
  let acc = 0;
  for (let i = 0; i < PLAYLIST.length; i++) {
    if (elapsed < acc + lengths[i]) {
      return { index: i, offset: elapsed - acc };
    }
    acc += lengths[i];
  }
  return { index: 0, offset: 0 };
}
